### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by nostra13** [helpcrunch/android-sdk-demo#23] opened 2021-01-17 14:39 UTC
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
       at com.helpcrunch.library.d.c.a$x.call(a.java:442)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at a.a.b.e.b(e.java:336)
       at a.a.b.e.c(e.java:284)
       at a.a.b.e.a(e.java:28)
       at a.a.b.e$b$b.call(e.java:123)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at a.a.b.c.b(c.java:372)
       at a.a.b.c.lambda$EpPtBzBqeced58fz7epZ1AHEq80(c.java:2)
       at a.a.b.-$$Lambda$c$EpPtBzBqeced58fz7epZ1AHEq80.a(-.java:2)
       at a.a.d.b$b.a(b.java:178)
       at a.a.b.c.c(c.java:364)
       at a.a.b.c.a(c.java:31)
       at a.a.b.c$e.call(c.java:340)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
       at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
       at io.socket.engineio.client.Socket$5.call(Socket.java:335)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
       at io.socket.engineio.client.Transport.onData(Transport.java:118)
       at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
       at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
       at io.socket.thread.EventThread$2.run(EventThread.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

`implementation "com.helpcrunch:chat-sdk:3.0.7"`

**Android:** 10

**Comment by TalbotGooday** [comment] 2021-01-18 08:20
Thanks for the report! Will be fixed in the next release
Duplicate of https://github.com/helpcrunch/android-sdk-demo/issues/21

**Closed** 2021-01-18 08:21 UTC
